import type { WatchListener } from "node:fs";
import fs from "node:fs";
import path from "node:path";
import type { RsbuildPlugin } from "@rsbuild/core";

type Options = {
  dir?: string;
  out?: string;
};

export default function pluginSvgTypes(options: Options = {}): RsbuildPlugin {
  const { dir = "src/assets/svg", out = "src/assets/svg/types.d.ts" } = options;

  function generate() {
    const absDir = path.resolve(dir);
    if (!fs.existsSync(absDir)) return;

    const files = fs
      .readdirSync(absDir)
      .filter((f) => f.endsWith(".svg"))
      .map((f) => path.basename(f, ".svg"));

    const union = files.map((f) => `"${f}"`).join(" | ") || "never";

    const content = `/**
 * WARNING: This file is auto-generated by plugin-svg-types.
 * Do not modify this file directly.
 * Generated at: ${new Date().toISOString()}
 */
export type SvgIconName = ${union};
`;

    fs.writeFileSync(path.resolve(out), content);
    console.log(`[pluginSvgTypes] 生成 icon types: ${files.length} 个`);
  }

  return {
    name: "svg-types-plugin",

    setup(api) {
      generate();
      let timer: NodeJS.Timeout | null = null;
      const listener: WatchListener<string> = (_, name) => {
        if (name?.endsWith(".svg")) {
          timer && clearTimeout(timer);
          timer = setTimeout(generate, 100);
        }
      };
      const watcher = fs.watch(dir, listener);
      api.onExit(watcher.close);
    },
  };
}
